@extends('layouts.app')
@section('title', $transaction->exists ? 'Edit transaksi' : 'Tambah transaksi')
@section('content')
<div class="page-heading reveal"><div><span class="eyebrow">{{ $transaction->exists ? 'PERBARUI CATATAN' : 'CATAT UANGMU' }}</span><h1>{{ $transaction->exists ? 'Edit transaksi' : 'Tambah transaksi' }}</h1><p>Isi detailnya dengan jelas supaya rekap lebih mudah dibaca.</p></div><a href="{{ route('transactions.index') }}" class="btn btn-outline">← Kembali</a></div>
<div class="form-layout"><section class="panel form-panel reveal"><form method="post" action="{{ $transaction->exists ? route('transactions.update', $transaction) : route('transactions.store') }}" class="form-stack">@csrf @if($transaction->exists) @method('PUT') @endif
    <div class="field"><label>Jenis transaksi</label><div class="type-selector"><label><input type="radio" name="type" value="expense" @checked(old('type', $transaction->type ?? request('type', 'expense')) === 'expense')><span><span class="type-icon expense">↗</span><strong>Pengeluaran</strong><small>Uang keluar</small></span></label><label><input type="radio" name="type" value="income" @checked(old('type', $transaction->type ?? request('type')) === 'income')><span><span class="type-icon income">↙</span><strong>Pemasukan</strong><small>Uang masuk</small></span></label></div></div>
    <div class="field"><label for="title">Untuk apa? <span class="required">*</span></label><input id="title" name="title" value="{{ old('title', $transaction->title) }}" placeholder="Contoh: Beli makan siang" maxlength="150" required></div>
    <div class="field-row"><div class="field"><label for="amount">Nominal (Rp) <span class="required">*</span></label><input id="amount" name="amount" type="number" inputmode="numeric" min="1" max="999999999999" value="{{ old('amount', $transaction->amount) }}" placeholder="0" required></div><div class="field"><label for="occurred_on">Tanggal <span class="required">*</span></label><input id="occurred_on" name="occurred_on" type="date" max="{{ now()->toDateString() }}" value="{{ old('occurred_on', $transaction->occurred_on?->toDateString() ?? now()->toDateString()) }}" required></div></div>
    <div class="field"><label for="category">Kategori <span class="required">*</span></label><select id="category" name="category" required><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category }}" @selected(old('category', $transaction->category) === $category)>{{ $category }}</option>@endforeach</select></div>
    <div class="field"><label for="notes">Catatan <span class="optional">Opsional</span></label><textarea id="notes" name="notes" rows="3" maxlength="1000" placeholder="Tambahkan detail jika perlu...">{{ old('notes', $transaction->notes) }}</textarea></div>
    <div class="form-actions"><a href="{{ route('transactions.index') }}" class="btn btn-outline">Batal</a><button class="btn btn-primary" type="submit">{{ $transaction->exists ? 'Simpan perubahan' : 'Simpan transaksi' }} <svg><use href="#i-arrow"/></svg></button></div>
</form></section><aside class="form-aside reveal"><span class="aside-icon"><svg><use href="#i-spark"/></svg></span><strong>Catat hari ini, tenang nanti.</strong><p>Saldo akan otomatis bertambah atau berkurang sesuai jenis transaksi yang kamu pilih.</p><div class="aside-line"></div><span>Tip: gunakan judul yang jelas agar transaksi mudah dicari kembali.</span></aside></div>
@endsection
