@extends('layouts.app')
@section('title', 'Transaksi')
@section('content')
<div class="page-heading reveal"><div><span class="eyebrow">CATATAN KEUANGAN</span><h1>Semua transaksi</h1><p>Setiap pemasukan dan pengeluaran, rapi di satu tempat.</p></div><a href="{{ route('transactions.create') }}" class="btn btn-primary"><svg><use href="#i-plus"/></svg> Tambah transaksi</a></div>
<section class="panel reveal"><form method="get" class="filter-bar"><div class="search-field"><span>⌕</span><input type="search" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Cari transaksi..."></div><select name="type" aria-label="Jenis transaksi"><option value="">Semua jenis</option><option value="income" @selected(($filters['type'] ?? '') === 'income')>Pemasukan</option><option value="expense" @selected(($filters['type'] ?? '') === 'expense')>Pengeluaran</option></select><input type="month" name="month" value="{{ $filters['month'] ?? '' }}" aria-label="Filter bulan"><button class="btn btn-outline btn-small" type="submit">Terapkan</button>@if($filters)<a href="{{ route('transactions.index') }}" class="reset-link">Reset</a>@endif</form>
<div class="section-divider"></div>
@if($transactions->isEmpty())<div class="empty-state"><span class="empty-icon"><svg><use href="#i-arrows"/></svg></span><strong>Belum ada transaksi ditemukan</strong><p>Coba ubah filter atau buat transaksi baru.</p><a href="{{ route('transactions.create') }}" class="btn btn-primary btn-small">Tambah transaksi</a></div>@else<div class="transaction-list full-list">@foreach($transactions as $item)<div class="transaction-row"><span class="transaction-icon {{ $item->type }}">{{ $item->type === 'income' ? '↙' : '↗' }}</span><div class="transaction-title"><strong>{{ $item->title }}</strong><span>{{ $item->category }} · {{ $item->occurred_on->translatedFormat('d F Y') }} @if($item->notes) · {{ Str::limit($item->notes, 50) }} @endif</span></div><strong class="transaction-amount {{ $item->type }}">{{ $item->type === 'income' ? '+' : '−' }} Rp {{ number_format($item->amount, 0, ',', '.') }}</strong><div class="row-actions"><a href="{{ route('transactions.edit', $item) }}" class="icon-button" aria-label="Edit {{ $item->title }}"><svg><use href="#i-edit"/></svg></a><form method="post" action="{{ route('transactions.destroy', $item) }}" data-confirm="Hapus transaksi ini? Saldo akan dihitung ulang.">@csrf @method('DELETE')<button type="submit" class="icon-button danger" aria-label="Hapus {{ $item->title }}"><svg><use href="#i-trash"/></svg></button></form></div></div>@endforeach</div><div class="pagination-wrap">{{ $transactions->links() }}</div>@endif
</section>
@endsection
