@extends('layouts.app')
@section('title', 'Rekap')
@section('content')
<div class="page-heading reveal"><div><span class="eyebrow">LIHAT GAMBARAN BESAR</span><h1>Rekap keuangan</h1><p>Pahami arus uangmu, hari demi hari dan bulan demi bulan.</p></div><a href="{{ route('reports.pdf', ['month' => $month]) }}" class="btn btn-primary"><svg><use href="#i-download"/></svg> Ekspor PDF</a></div>
<form class="report-filter reveal" method="get"><div><strong>Pilih bulan</strong><span>Rekap harian tersedia untuk setiap tanggal dalam bulan.</span></div><div class="report-filter-actions"><input type="month" name="month" value="{{ $month }}" aria-label="Pilih bulan"><button type="submit" class="btn btn-outline btn-small">Tampilkan</button></div></form>
<div class="report-summary"><div class="metric-card reveal"><div class="metric-top"><span class="metric-icon income">↗</span><span class="metric-period">{{ $date->translatedFormat('F Y') }}</span></div><p>Total pemasukan</p><strong>Rp {{ number_format($income, 0, ',', '.') }}</strong></div><div class="metric-card reveal"><div class="metric-top"><span class="metric-icon expense">↘</span><span class="metric-period">{{ $date->translatedFormat('F Y') }}</span></div><p>Total pengeluaran</p><strong>Rp {{ number_format($expense, 0, ',', '.') }}</strong></div><div class="metric-card net-card reveal"><div class="metric-top"><span class="metric-icon net">◎</span><span class="metric-period">Selisih</span></div><p>Arus bersih</p><strong class="{{ $income - $expense < 0 ? 'negative' : '' }}">{{ $income - $expense < 0 ? '−' : '+' }} Rp {{ number_format(abs($income - $expense), 0, ',', '.') }}</strong></div></div>
<div class="content-grid report-grid"><section class="panel reveal"><div class="panel-head"><div><span class="eyebrow">PER TANGGAL</span><h2>Rekap harian</h2></div><span class="panel-subtitle">{{ $date->translatedFormat('F Y') }}</span></div><div class="table-scroll"><table class="data-table"><thead><tr><th>Tanggal</th><th>Pemasukan</th><th>Pengeluaran</th></tr></thead><tbody>@foreach($days as $day)<tr class="{{ !$day['income'] && !$day['expense'] ? 'quiet-row' : '' }}"><td>{{ \Carbon\Carbon::parse($day['date'])->translatedFormat('d M Y') }}</td><td class="income-text">{{ $day['income'] ? 'Rp '.number_format($day['income'], 0, ',', '.') : '—' }}</td><td class="expense-text">{{ $day['expense'] ? 'Rp '.number_format($day['expense'], 0, ',', '.') : '—' }}</td></tr>@endforeach</tbody></table></div></section>
<section class="panel category-panel reveal"><div class="panel-head"><div><span class="eyebrow">KATEGORI</span><h2>Ke mana uang pergi?</h2></div></div>@if($categories->isEmpty())<div class="mini-empty">Belum ada pengeluaran bulan ini.</div>@else<div class="category-list">@foreach($categories as $category => $amount)<div class="category-row"><div class="category-title"><strong>{{ $category }}</strong><span>Rp {{ number_format($amount, 0, ',', '.') }}</span></div><div class="progress-track"><div style="width: {{ $expense > 0 ? round($amount / $expense * 100) : 0 }}%"></div></div></div>@endforeach</div>@endif</section></div>
<section class="panel transactions-panel reveal"><div class="panel-head"><div><span class="eyebrow">RINCIAN BULAN INI</span><h2>Daftar transaksi</h2></div><span class="panel-subtitle">{{ $transactions->count() }} transaksi</span></div>@if($transactions->isEmpty())<div class="mini-empty">Belum ada transaksi bulan ini.</div>@else<div class="transaction-list">@foreach($transactions->reverse() as $item)<div class="transaction-row"><span class="transaction-icon {{ $item->type }}">{{ $item->type === 'income' ? '↙' : '↗' }}</span><div class="transaction-title"><strong>{{ $item->title }}</strong><span>{{ $item->category }} · {{ $item->occurred_on->translatedFormat('d M Y') }}</span></div><strong class="transaction-amount {{ $item->type }}">{{ $item->type === 'income' ? '+' : '−' }} Rp {{ number_format($item->amount, 0, ',', '.') }}</strong></div>@endforeach</div>@endif</section>
@endsection
