@extends('layouts.app')
@section('title', 'Pengaturan')
@section('content')
<div class="page-heading reveal"><div><span class="eyebrow">AKUN & DATA</span><h1>Pengaturan</h1><p>Atur saldo, target, dan keamanan akun pribadimu.</p></div></div>
<div class="settings-grid"><section class="panel form-panel reveal"><div class="panel-head"><div><span class="eyebrow">PROFIL KEUANGAN</span><h2>Pengaturan utama</h2></div></div><form method="post" action="{{ route('settings.update') }}" class="form-stack">@csrf @method('PUT')<div class="field"><label for="name">Nama</label><input id="name" name="name" value="{{ old('name', auth()->user()->name) }}" required maxlength="80"></div><div class="field"><label for="opening_balance">Saldo awal (Rp)</label><input id="opening_balance" name="opening_balance" type="number" inputmode="numeric" min="-999999999999" max="999999999999" value="{{ old('opening_balance', auth()->user()->opening_balance) }}" required><small>Saldo sebelum transaksi yang tersimpan. Mengubahnya akan memengaruhi saldo sekarang.</small></div><div class="field"><label for="monthly_budget">Target pengeluaran bulanan (Rp) <span class="optional">Opsional</span></label><input id="monthly_budget" name="monthly_budget" type="number" inputmode="numeric" min="1" max="999999999999" value="{{ old('monthly_budget', auth()->user()->monthly_budget) }}" placeholder="Contoh: 3000000"></div><button class="btn btn-primary" type="submit">Simpan pengaturan</button></form></section>
<section class="panel form-panel reveal"><div class="panel-head"><div><span class="eyebrow">KEAMANAN</span><h2>Ubah kata sandi</h2></div></div><form method="post" action="{{ route('settings.password') }}" class="form-stack">@csrf @method('PUT')<div class="field"><label for="current_password">Kata sandi saat ini</label><input id="current_password" type="password" name="current_password" required autocomplete="current-password"></div><div class="field"><label for="password">Kata sandi baru</label><input id="password" type="password" name="password" required minlength="8" autocomplete="new-password"></div><div class="field"><label for="password_confirmation">Ulangi kata sandi baru</label><input id="password_confirmation" type="password" name="password_confirmation" required minlength="8" autocomplete="new-password"></div><button class="btn btn-outline" type="submit">Perbarui kata sandi</button></form></section></div>
<section class="panel cleanup-panel reveal"><div class="cleanup-copy"><span class="eyebrow">KELOLA PENYIMPANAN</span><h2>Bersihkan data lama</h2><p>Hapus transaksi sebelum {{ \Carbon\Carbon::parse($cutoff)->translatedFormat('d F Y') }} agar database tetap ringan. Nilai bersih transaksi tersebut akan dipindahkan ke saldo awal, sehingga saldo saat ini tetap sama.</p><span class="old-count">{{ $oldCount }} transaksi dapat dibersihkan</span></div><form method="post" action="{{ route('settings.prune') }}" data-confirm="Hapus {{ $oldCount }} transaksi lama secara permanen? Pastikan rekap PDF sudah diunduh jika diperlukan.">@csrf<div class="field"><label for="confirmation">Ketik HAPUS untuk konfirmasi</label><input id="confirmation" name="confirmation" required pattern="HAPUS" placeholder="HAPUS" {{ $oldCount === 0 ? 'disabled' : '' }}></div><button type="submit" class="btn btn-danger" {{ $oldCount === 0 ? 'disabled' : '' }}><svg><use href="#i-trash"/></svg> Bersihkan transaksi lama</button></form></section>
@endsection

